// Legal disclaimer footer — place at the bottom of all public-facing pages.

export function LegalFooter({ standalone = false }: { standalone?: boolean }) {
  return (
    <footer className={`px-6 py-12 text-xs text-gray-500 max-w-5xl mx-auto${standalone ? " border-t border-white/10 mt-24" : ""}`}>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
        <div>
          <p className="text-gray-300 font-medium mb-2">Disclaimer</p>
          <p className="mb-2">
            Omnyra provides AI-generated content strategies and hook suggestions based on predictive
            modeling. Virality is not guaranteed — outputs only increase the likelihood of performance
            based on predictive modeling.
          </p>
          <p className="mb-2">
            All results are estimates and should be treated as creative guidance only. Actual
            performance depends on platform algorithms, audience behavior, timing, and external
            factors outside of Omnyra&apos;s control.
          </p>
          <p className="text-gray-600">
            Past performance or predicted engagement does not indicate future results.
          </p>
        </div>

        <div className="space-y-4">
          <div>
            <p className="text-gray-300 font-medium mb-1">AI Usage Notice</p>
            <p>
              Content generated by Omnyra is produced using artificial intelligence. Users are
              responsible for final review, selection, and publishing decisions.
            </p>
          </div>

          <div>
            <p className="text-gray-300 font-medium mb-1">No Guarantees</p>
            <p>
              Omnyra does not guarantee viral reach, engagement levels, follower growth, or platform
              performance outcomes.
            </p>
          </div>
        </div>
      </div>

      <div className="border-t border-white/5 pt-6 flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div className="flex flex-wrap gap-4">
          <a href="/legal/terms" className="hover:text-gray-300 transition-colors">Terms & Conditions</a>
          <a href="/legal/privacy" className="hover:text-gray-300 transition-colors">Privacy Policy</a>
          <a href="/legal/refund" className="hover:text-gray-300 transition-colors">Refund Policy</a>
          <a href="/faq" className="hover:text-gray-300 transition-colors">FAQ</a>
        </div>
        <div className="flex flex-col gap-1">
          <span>Intellectual Property: Omnyra retains ownership of all system architecture, scoring models, and underlying logic.</span>
          <span>
            Contact:{" "}
            <a href="mailto:info@omnyra.studio" className="text-blue-500 hover:text-blue-400">
              info@omnyra.studio
            </a>
          </span>
        </div>
      </div>

      <p className="mt-6 text-gray-600">
        &copy; {new Date().getFullYear()} Omnyra. All rights reserved. Users retain full responsibility
        for how generated content is used and published across platforms.
      </p>
    </footer>
  );
}
