export const metadata = { title: "Terms & Conditions — Omnyra" };

export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-16 text-sm text-gray-200 leading-relaxed">
      <h1 className="text-2xl font-bold text-white mb-2">Terms & Conditions</h1>
      <p className="text-gray-400 mb-10">Last updated: June 2026</p>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">1. Introduction</h2>
        <p>
          Omnyra (&quot;the Service&quot;) is an AI-powered content strategy platform that generates hook variants,
          video strategies, and creative guidance using predictive modeling. By accessing or using the Service,
          you agree to be bound by these Terms & Conditions. If you do not agree, you must not use the Service.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">2. Acceptance of Terms</h2>
        <p>
          These Terms constitute a legally binding agreement between you and Omnyra. We reserve the right to
          update these Terms at any time. Continued use of the Service following any update constitutes
          acceptance of the revised Terms.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">3. Service Description</h2>
        <p>
          Omnyra generates AI-powered content hooks, video strategies, scoring outputs, and creative
          recommendations. All outputs are advisory only. The Service does not guarantee any particular
          performance outcome. Results are probabilistic estimates based on predictive modeling, not
          guaranteed performance metrics.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">4. User Responsibilities</h2>
        <ul className="list-disc pl-5 space-y-1">
          <li>You must use the Service only for lawful purposes.</li>
          <li>You must comply with all applicable platform rules (TikTok, YouTube, Instagram, etc.).</li>
          <li>You are solely responsible for reviewing, editing, and publishing all generated content.</li>
          <li>You must not use the Service to automate spam or engage in abusive behavior.</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">5. Acceptable Use</h2>
        <p className="mb-2">The following are strictly prohibited:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Generation or distribution of illegal, harmful, or harassing content</li>
          <li>Use of the Service to reverse-engineer proprietary systems</li>
          <li>Automated abuse or API scraping beyond permitted usage</li>
          <li>Misrepresentation of AI-generated content as human-authored without disclosure</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">6. Intellectual Property</h2>
        <p>
          Omnyra retains ownership of all system architecture, scoring models, algorithms, and underlying
          logic. You retain ownership of your input content. Generated outputs are licensed to you for
          personal and commercial use, subject to these Terms. You may not sublicense or resell the
          underlying system or its outputs as a competing service.
        </p>
      </section>

      <section className="mb-8 border border-yellow-500/30 rounded-lg p-4 bg-yellow-500/5">
        <h2 className="text-lg font-semibold text-yellow-400 mb-3">7. Disclaimers</h2>
        <p className="mb-3">
          Outputs generated by Omnyra are produced using artificial intelligence. The Service is provided
          on an &quot;as is&quot; basis without warranties of any kind, express or implied.
        </p>
        <p className="mb-3 font-medium text-white">
          Virality is not guaranteed — outputs only increase the likelihood of performance based on
          predictive modeling.
        </p>
        <p className="mb-3">
          Past performance or predicted engagement does not indicate future results. Actual content
          performance depends on platform algorithms, audience behavior, timing, and external factors
          entirely outside Omnyra&apos;s control.
        </p>
        <p>
          Omnyra does not guarantee viral reach, engagement levels, follower growth, or any specific
          platform performance outcomes.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">8. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by applicable law, Omnyra shall not be liable for any indirect,
          incidental, consequential, or punitive damages, including loss of revenue, loss of engagement,
          or platform penalties arising from use of the Service. Our total aggregate liability shall not
          exceed the amount you paid for the Service in the twelve months preceding the claim.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">9. Termination</h2>
        <p>
          We reserve the right to suspend or terminate your access to the Service at any time for
          violations of these Terms, without prior notice. You may terminate your account at any time
          through your account settings.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">10. Governing Law</h2>
        <p>
          These Terms shall be governed by and construed in accordance with the laws of the jurisdiction
          in which Omnyra operates, without regard to conflict of law principles.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">11. Changes to Terms</h2>
        <p>
          We may update these Terms at any time. We will notify users of material changes via email or
          in-app notification. Continued use of the Service after updates constitutes acceptance of the
          revised Terms.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">12. Contact</h2>
        <p>
          For legal inquiries or support, contact us at:{" "}
          <a href="mailto:info@omnyra.studio" className="text-blue-400 underline">info@omnyra.studio</a>
        </p>
      </section>
    </main>
  );
}
