-- Scripts and Shot Plans schema
--
-- scripts: stores approved scripts linked to projects/briefs
-- shot_plans: one per generation run, holds the motion_map metadata
-- shots: individual shot packets generated by the Director engine

-- ── scripts ───────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS scripts (
  id                        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id                UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id                   UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  brief_id                  UUID REFERENCES briefs(id) ON DELETE SET NULL,
  hook_id                   UUID REFERENCES hooks(id) ON DELETE SET NULL,
  content                   TEXT NOT NULL,
  platform                  TEXT,
  estimated_duration_seconds FLOAT,
  status                    TEXT NOT NULL DEFAULT 'draft'
                              CHECK (status IN ('draft','approved','archived')),
  created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_scripts_project_id ON scripts(project_id);
CREATE INDEX IF NOT EXISTS idx_scripts_user_id    ON scripts(user_id);

ALTER TABLE scripts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "scripts_owner_all" ON scripts
  FOR ALL USING (auth.uid() = user_id);

CREATE TRIGGER scripts_set_updated_at
  BEFORE UPDATE ON scripts
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ── shot_plans ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS shot_plans (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  script_id   UUID NOT NULL REFERENCES scripts(id) ON DELETE CASCADE,
  project_id  UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  platform    TEXT,
  motion_map  JSONB NOT NULL DEFAULT '{}'::jsonb,
  status      TEXT NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending','ready','rendering','complete')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_shot_plans_script_id  ON shot_plans(script_id);
CREATE INDEX IF NOT EXISTS idx_shot_plans_project_id ON shot_plans(project_id);

ALTER TABLE shot_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "shot_plans_owner_all" ON shot_plans
  FOR ALL USING (
    auth.uid() = (SELECT user_id FROM scripts WHERE id = script_id LIMIT 1)
  );

-- ── shots ─────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS shots (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  shot_plan_id        UUID NOT NULL REFERENCES shot_plans(id) ON DELETE CASCADE,
  script_id           UUID NOT NULL REFERENCES scripts(id) ON DELETE CASCADE,
  project_id          UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  shot_id             TEXT NOT NULL,
  shot_number         INTEGER NOT NULL,
  attention_function  TEXT NOT NULL
                        CHECK (attention_function IN (
                          'pattern_interrupt','curiosity_spike','trust_grounding',
                          'tension_escalation','emotional_release','desire_activation',
                          'urgency_trigger','pacing_reset'
                        )),
  purpose_rationale   TEXT NOT NULL,
  duration_seconds    FLOAT NOT NULL,
  energy_curve        TEXT NOT NULL
                        CHECK (energy_curve IN ('spike','ramp_up','ramp_down','sustain','pulse')),
  camera_behavior     TEXT NOT NULL
                        CHECK (camera_behavior IN (
                          'static','slow_push_in','dolly_in','handheld_drift',
                          'crane_up','whip_pan','orbital_slow'
                        )),
  motion_intensity    FLOAT NOT NULL CHECK (motion_intensity BETWEEN 0.0 AND 1.0),
  framing             TEXT NOT NULL
                        CHECK (framing IN (
                          'extreme_closeup','closeup','medium_closeup','medium','wide'
                        )),
  content_type        TEXT NOT NULL
                        CHECK (content_type IN ('avatar','broll','text_overlay','transition')),
  visual_prompt       TEXT NOT NULL,
  render_assignment   TEXT NOT NULL CHECK (render_assignment IN ('avatar','fal')),
  fal_model           TEXT,
  transition_in       TEXT NOT NULL
                        CHECK (transition_in IN (
                          'hard_cut','soft_dissolve','whip_blur','light_streak'
                        )),
  transition_duration FLOAT NOT NULL DEFAULT 0.0,
  audio_intent        TEXT NOT NULL,
  fatigue_risk        FLOAT NOT NULL CHECK (fatigue_risk BETWEEN 0.0 AND 1.0),
  render_job_id       UUID,
  render_status       TEXT DEFAULT 'pending',
  render_url          TEXT,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_shots_shot_plan_id ON shots(shot_plan_id);
CREATE INDEX IF NOT EXISTS idx_shots_project_id   ON shots(project_id);
CREATE INDEX IF NOT EXISTS idx_shots_shot_number  ON shots(shot_plan_id, shot_number);

ALTER TABLE shots ENABLE ROW LEVEL SECURITY;

CREATE POLICY "shots_owner_all" ON shots
  FOR ALL USING (
    auth.uid() = (SELECT user_id FROM scripts WHERE id = script_id LIMIT 1)
  );
