-- Weekly insights generated by the AI insight engine.
-- One row per user per week. Surfaced in the "What Omnyra Learned" panel.

CREATE TABLE IF NOT EXISTS weekly_insights (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  week_start    DATE NOT NULL,
  subject       TEXT NOT NULL,
  body          TEXT NOT NULL,
  insights      JSONB NOT NULL DEFAULT '{}'::jsonb,
  sent_at       TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, week_start)
);

CREATE INDEX IF NOT EXISTS idx_weekly_insights_user_id ON weekly_insights(user_id);

ALTER TABLE weekly_insights ENABLE ROW LEVEL SECURITY;

CREATE POLICY "weekly_insights_owner_read" ON weekly_insights
  FOR SELECT USING (auth.uid() = user_id);
-- Inserts/updates via service_role only (cron)
