/**
 * POST /api/generate-scene-images
 *
 * Scene Compiler pipeline:
 *   User input → compileSceneGraph() → SceneCompilerProject
 *   → scene.image_prompt → Flux Dev (28 steps) → 4 photorealistic scene images
 *
 * The compiler generates a deterministic scene graph with:
 *   - Forced narrative structure (hook/development/climax/resolution)
 *   - Forced shot diversity (wide/medium/close-up/medium-wide)
 *   - Character appearance lock across all scenes
 *   - Continuity metadata for the video pipeline
 *
 * Body:    { script, concept, hook?, targetAudience?, characterRef?, niche?, referenceImages? }
 * Returns: { scenes: [{ prompt, description, script_part, image_url, angle }], sceneGraph: SceneCompilerProject }
 * Cost:    12 credits (4 × image_standard)
 */

import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";
import { logUsageEvent } from "@/lib/cache";
import { withCreditState, InsufficientCreditsError } from "@/lib/credits/withCreditState";
import { CREDIT_COSTS } from "@/lib/rules/creditRules";
import { type StoryBeat } from "@/lib/storyboard-planner";
import { compileSceneGraph, buildFluxPromptFromScene } from "@/lib/services/scene-compiler";
import type { SceneCompilerProject } from "@/lib/types/scene-compiler";

export const maxDuration = 120;

const SCENE_COUNT = 4;

// ── POST handler ──────────────────────────────────────────────────────────────

export async function POST(req: Request) {
  const cookieStore = await cookies();
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    { cookies: { getAll: () => cookieStore.getAll(), setAll: () => {} } },
  );
  const { data: { user }, error: authErr } = await supabase.auth.getUser();
  if (authErr || !user) return Response.json({ error: "Unauthorized" }, { status: 401 });

  const falKey = process.env.FAL_API_KEY ?? process.env.FALAI_API_KEY;
  if (!falKey) return Response.json({ error: "FAL_API_KEY not configured" }, { status: 503 });
  if (!process.env.ANTHROPIC_API_KEY) {
    return Response.json({ error: "ANTHROPIC_API_KEY not configured" }, { status: 503 });
  }

  let body: {
    script?:          string;
    concept?:         string;
    hook?:            string;
    targetAudience?:  string;
    characterRef?:    string;
    niche?:           string;
    referenceImages?: string[];
  };
  try { body = await req.json(); }
  catch { return Response.json({ error: "Invalid JSON" }, { status: 400 }); }

  const { script, concept, hook, targetAudience, characterRef, niche, referenceImages } = body;
  if (!script?.trim())  return Response.json({ error: "script is required" }, { status: 400 });
  if (!concept?.trim()) return Response.json({ error: "concept is required" }, { status: 400 });

  const creditCost = CREDIT_COSTS.image_standard * SCENE_COUNT;

  type Scene = { prompt: string; description: string; script_part: string; image_url: string; angle: string };

  try {
    const result = await withCreditState<{ scenes: Scene[]; beats: StoryBeat[]; sceneGraph: SceneCompilerProject }>({
      userId: user.id,
      cost:   creditCost,
      run:    async () => {

        // ── Step 1: Compile scene graph ─────────────────────────────────────
        console.log(`[SCENE_IMAGES] compiling scene graph niche=${niche ?? "default"} scenes=${SCENE_COUNT}`);
        const sceneGraph = await compileSceneGraph({
          script:          script.trim(),
          concept:         concept.trim(),
          hook:            hook,
          targetAudience:  targetAudience,
          characterRef:    characterRef,
          niche:           niche,
          referenceImages: referenceImages,
          aspectRatio:     "9:16",
          sceneCount:      SCENE_COUNT,
        });

        // ── Step 2: Generate all images in parallel via Flux Dev ─────────────
        // Flux Dev follows prompts precisely (28 steps, guidance 3.5)
        // Each scene has a distinct image_prompt generated by the compiler
        const imageResults: Scene[] = await Promise.all(
          sceneGraph.scene_graph.map(async (scene, i) => {
            const finalPrompt = buildFluxPromptFromScene(scene, sceneGraph);

            console.log(`[FLUX_PROMPT] scene=${i + 1} role=${scene.narrative_role} shot=${scene.camera?.shot_type}: ${finalPrompt.substring(0, 180)}`);

            const res = await fetch("https://fal.run/fal-ai/flux/dev", {
              method:  "POST",
              headers: {
                Authorization:  `Key ${falKey}`,
                "Content-Type": "application/json",
              },
              body: JSON.stringify({
                prompt:                finalPrompt,
                num_images:            1,
                image_size:            { width: 1080, height: 1920 },
                num_inference_steps:   28,
                guidance_scale:        3.5,
                enable_safety_checker: true,
              }),
            });

            if (!res.ok) {
              const errText = await res.text();
              console.error(`[SCENE_IMAGES] fal error scene=${i + 1}:`, errText.substring(0, 200));
              throw new Error(`Fal image generation failed for scene ${i + 1}`);
            }

            const data = await res.json() as { images?: { url: string }[] };
            const imageUrl = data.images?.[0]?.url;
            if (!imageUrl) throw new Error(`Fal returned no image URL for scene ${i + 1}`);

            console.log(`[FLUX_DONE] scene=${i + 1} url=${imageUrl.substring(0, 60)}`);

            return {
              prompt:      finalPrompt,
              description: scene.narrative_role,
              script_part: scene.character_state.emotion,
              image_url:   imageUrl,
              angle:       `${scene.narrative_role.toUpperCase()}_${scene.camera.shot_type.replace(/\s/g, "_")}`,
            };
          }),
        );

        // Build StoryBeat array for backwards-compat with video pipeline
        const beats: StoryBeat[] = sceneGraph.scene_graph.map((scene, i) => ({
          beatNumber:       i + 1,
          purpose:          scene.narrative_role,
          emotion:          scene.character_state.emotion,
          bodyLanguage:     scene.character_state.action_state,
          composition:      scene.camera.shot_type,
          lighting:         sceneGraph.global_style.lighting,
          keyAction:        scene.video_prompt,
          environmentFocus: scene.environment.location,
        }));

        return { data: { scenes: imageResults, beats, sceneGraph } };
      },
    });

    logUsageEvent(user.id, "generate-scene-images", "generate", creditCost, { concept });
    return Response.json(result);

  } catch (err) {
    if (err instanceof InsufficientCreditsError) {
      return Response.json({
        error:    "INSUFFICIENT_CREDITS",
        balance:  err.balance,
        required: err.cost,
        planType: err.planType,
      }, { status: 402 });
    }
    const msg = err instanceof Error ? err.message : String(err);
    console.error("[generate-scene-images]", msg);
    return Response.json({ error: msg || "Scene image generation failed" }, { status: 500 });
  }
}
